### ISSUE TITLE
python tasks/run.py --config=egs/datasets/can/lm3d_radnerf_sr.yaml --exp_name=motion2video_nerf/may_head --reset

### ISSUE THREAD

**Issue by einsqing** [yerfor/GeneFacePlusPlus#10]
![1706941106185](https://github.com/yerfor/GeneFacePlusPlus/assets/7685948/83d6bf6c-c379-45ec-a623-d1bca7e62b74)

tensors used as indices must be long, byte or bool tensors

**Comment by yerfor** [comment]
Hi, please check whether the CUDA extensions are installed correctly. For instance, whether the CUDA version and the python cudatoolkit version are the same.

**Comment by danyow-cheung** [comment]
thank to the great work, here is my env,which is testable in the radnerf.but i got the same issue in this project 
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/76671016/5e18e45c-a0cb-4add-a4dc-737e0dae97fd)

**Comment by danyow-cheung** [comment]
same issue even though i changed my `nvcc --version`
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/76671016/b2380262-6c7f-44fc-b51d-d78adf7489e4)

**Comment by yerfor** [comment]
Thanks for reporting the bug. `cond_mask` is a deprecated feature and we will delete it in our next commit.
