### ISSUE TITLE
Head size and pose is not stable at inference

### ISSUE THREAD

**Issue by Gina07** [yerfor/GeneFacePlusPlus#104]
Greets! thanks for this good work. I found that the rendered head size and pose is not stable at inference. (头部忽大忽小，头部的位姿总是在快速变化，整体给人感觉不太连续) I checked the head pose is quite stable in the training dataset. Do you have any clues or suggestions on this? Thanks a lot.

https://github.com/yerfor/GeneFacePlusPlus/assets/9716015/45eed8a4-b1d1-4728-8607-b76f0e6e4b96

**Comment by Net-Maker** [comment]
训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口

**Comment by Gina07** [comment]
> 训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口

ambient_loss不是调节面部之外区域的抖动问题的吗?现在是头整体都比较抖动，这个有用吗？应该怎么调整呢？看作者说增加landmark smooth win size会都在嘴型过于平滑。。。

**Comment by Net-Maker** [comment]
这都是因数据而异的，在egs/datasets里面找到你的config文件就可以调了，多实验几次，多看看tensorboard，或者用训练中途的ckpt推理一下对比结果，才能找到最适合这个数据的参数

**Comment by guyanxiao** [comment]
> > > 训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口
> > 
> > 
> > ambient_loss不是调节面部之外区域的抖动问题的吗?现在是头整体都比较抖动，这个有用吗？应该怎么调整呢？看作者说增加landmark smooth win size会都在嘴型过于平滑。。。
> 
> 你好，我们对ambient loss做了改进，现在ambient loss可以改善头部抖动的问题，具体可以看这个demo：https://genefaceplusplus.github.io/static/videos/w_wo_nonface_reg.mp4

最近的更新中没有看到non-face reg loss的更新，请问代码发布了么？

**Comment by Net-Maker** [comment]
请问是使用segmap对非面部区域做了一个reg _loss吗？

**Comment by yerfor** [comment]
现在的ambient loss会对非面部区域算loss，而之前是只对环境区域算loss。

**Comment by Net-Maker** [comment]
Cool！ 期待您的更新

**Comment by Gina07** [comment]
> > > 训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口
> > 
> > 
> > ambient_loss不是调节面部之外区域的抖动问题的吗?现在是头整体都比较抖动，这个有用吗？应该怎么调整呢？看作者说增加landmark smooth win size会都在嘴型过于平滑。。。
> 
> 你好，我们对ambient loss做了改进，现在ambient loss可以改善头部抖动的问题，具体可以看这个demo：https://genefaceplusplus.github.io/static/videos/w_wo_nonface_reg.mp4

Hello, thanks for the reply. with adaptive ambient loss, now the head size and hair is much more stable. But I found the mouth region is less clear than other face region, like the teeth and lips are sometimes blurred. Do you have any suggestions on how to improve this? Many thanks.

**Comment by yerfor** [comment]
> > > > 训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口
> > > 
> > > 
> > > ambient_loss不是调节面部之外区域的抖动问题的吗?现在是头整体都比较抖动，这个有用吗？应该怎么调整呢？看作者说增加landmark smooth win size会都在嘴型过于平滑。。。
> > 
> > 
> > 你好，我们对ambient loss做了改进，现在ambient loss可以改善头部抖动的问题，具体可以看这个demo：https://genefaceplusplus.github.io/static/videos/w_wo_nonface_reg.mp4
> 
> Hello, thanks for the reply. with adaptive ambient loss, now the head size and hair is much more stable. But I found the mouth region is less clear than other face region, like the teeth and lips are sometimes blurred. Do you have any suggestions on how to improve this? Many thanks.

You can try to increase `hparams['lambda_lpips_loss']`, please refer to the calculation process of `sr_lip_lpips_loss`

**Comment by kike-0304** [comment]
> > > 训练头部的时候没训好，调一调ambient_loss，检查一下数据处理得怎么样，增加landmark的平滑窗口
> > 
> > 
> > ambient_loss不是调节面部之外区域的抖动问题的吗?现在是头整体都比较抖动，这个有用吗？应该怎么调整呢？看作者说增加landmark smooth win size会都在嘴型过于平滑。。。
> 
> 你好，我们对ambient loss做了改进，现在ambient loss可以改善头部抖动的问题，具体可以看这个demo：https://genefaceplusplus.github.io/static/videos/w_wo_nonface_reg.mp4

请问这个改动的代码具体在哪一部分？

**Comment by Net-Maker** [comment]
作者阐述的就是他提出ambient_loss的过程，具体的你可以去看ambient_loss在训练中的计算过程，同时，我发现头部抖动可能和相机位姿不准有关系，我优化了pose，并实现了更稳定的头部推理
