### ISSUE TITLE
Add Google colab?

### ISSUE THREAD

**Issue by yyheart** [yerfor/GeneFacePlusPlus#12]
Pl.thks

**Comment by yerfor** [comment]
Yes, we will implement google colab in few days. Thanks for your advice.

**Comment by WHalcyon** [comment]
> Yes, we will implement google colab in few days. Thanks for your advice.

I've gotten the may.mp4 inference demo working simply by following most of the provided instructions. I have not yet tried fine tuning, will report after I try.

Colab uses CUDA 12, which is not friendly to torch-ngp but it works by replacing all instances of "c++14" with "c++17" and deleting the "-use_fast_math" flag in all python scripts in all 4 torch-ngp modules. Do not downgrade any torch related module or change the CUDA installation, this will cause runtime errors.

Thanks for all your work, and happy new year.

**Comment by Kizuna-AII** [comment]
We have just updated Google colab!
Thanks for your valuable advice!
