### ISSUE TITLE
AttributeError: 'int' object has no attribute 'item' | WARNING: ERROR calculating ambient loss

### ISSUE THREAD

**Issue by m000lie** [yerfor/GeneFacePlusPlus#136]
sometimes when im running the training script, i will be faced with an error like that:

Traceback (most recent call last):
  File "/workspace/GeneFacePPAI/tasks/radnerfs/radnerf_sr.py", line 293, in _training_step
    current_ambient_loss = loss_output['ambient_loss'].item()
AttributeError: 'int' object has no attribute 'item'
| WARNING: ERROR calculating ambient loss
![Screenshot 2024-03-17 at 19 53 41](https://github.com/yerfor/GeneFacePlusPlus/assets/76882804/eb8a78e3-32d6-400e-a38f-19076912f0f6)

why does this happen? it will continuously print that error until terminated. i have to restart the training sequence over again from scratch as if i resume training, it will just default to printing that error.

**Comment by m000lie** [comment]
sorry dumb question, this just means that the model has converged (i.e. learnt to the best of it's ability) and it can no longer proceed.

**Comment by keqixiaojie** [comment]
so why it means that the model has converged？I‘m still confused.
