### ISSUE TITLE
how to set batch_size during training

### ISSUE THREAD

**Issue by jinqinn** [yerfor/GeneFacePlusPlus#144]
how to set batch_size during training

**Comment by pxssw** [comment]
./tasks/radnerfs/dataset_utils.py", line 440, in collater
    assert len(samples) == 1 # NeRF only take 1 image for each iteration

**Comment by pxssw** [comment]
> how to set batch_size during training

./tasks/radnerfs/dataset_utils.py", line 440, in collater
assert len(samples) == 1 # NeRF only take 1 image for each iteration

**Comment by jinqinn** [comment]
@pxssw thanks
