### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by huiceli** [yerfor/GeneFacePlusPlus#148]
执行export PYTHONPATH=./
python inference/genefacepp_infer.py --a2m_ckpt=checkpoints/audio2motion_vae --head_ckpt= --torso_ckpt=checkpoints/motion2video_nerf/may_torso --drv_aud=data/raw/val_wavs/MacronSpeech.wav --out_name=may_demo.mp4
时遇到报错
| WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints/th1kh_512_audio2motion/base.yaml not exist.
| Hparams:  {
  "accumulate_grad_batches": 1,
  "amp": false,
  "audio_type": "hubert",
  "base_config": [
    "egs/egs_bases/audio2motion/vae.yaml",
    "../th1kh_512_audio2motion/base.yaml"
  ],
  "batch_size": 4,
  "binarization_args": {
    "with_coeff": true,
    "with_hubert": true,
    "with_mel": true
  },
  "binary_data_dir": "data/binary/voxceleb2_audio2motion",
  "blink_mode": "blink_unit",
  "clip_grad_norm": 1,
  "clip_grad_value": 0,
  "debug": false,
  "ds_name": "TH1KH_512",
  "eval_max_batches": 10,
  "exp_name": "",
  "gen_dir_name": "",
  "hidden_size": 256,
  "infer": false,
  "infer_audio_source_name": "",
  "infer_ckpt_steps": 40000,
  "infer_out_npy_name": "",
  "init_from_ckpt": "",
  "init_method": "tcp",
  "lambda_kl": 0.02,
  "lambda_kl_t1": 2000,
  "lambda_kl_t2": 2000,
  "lambda_l2_reg_exp": 0.1,
  "lambda_mse_exp": 1.0,
  "lambda_mse_lm2d": 0.0,
  "lambda_mse_lm3d": 0.0,
  "load_ckpt": "",
  "load_db_to_memory": false,
  "lr": 0.0005,
  "max_sentences_per_batch": 512,
  "max_tokens_per_batch": 20000,
  "max_updates": 400000,
  "motion_type": "exp",
  "num_ckpt_keep": 100,
  "num_sanity_val_steps": 5,
  "num_valid_plots": 1,
  "num_workers": 4,
  "optimizer_adam_beta1": 0.9,
  "optimizer_adam_beta2": 0.999,
  "print_nan_grads": false,
  "process_id": 0,
  "raw_data_dir": "/home/tiger/datasets/raw/TH1KH_512",
  "ref_id_mode": "first_frame",
  "resume_from_checkpoint": 0,
  "sample_min_length": 32,
  "save_best": false,
  "save_codes": [
    "tasks",
    "modules",
    "egs"
  ],
  "save_gt": true,
  "scheduler": "exponential",
  "seed": 9999,
  "smo_win_size": 5,
  "split_seed": 999,
  "start_rank": 0,
  "syncnet_ckpt_dir": "checkpoints/0904_syncnet/syncnet_hubert_vox2",
  "task_cls": "tasks.os_avatar.audio2secc_task.Audio2SECCTask",
  "tb_log_interval": 100,
  "total_process": 1,
  "use_eye_amp_embed": false,
  "use_flow": true,
  "use_fork": true,
  "use_kv_dataset": true,
  "use_mouth_amp_embed": true,
  "use_pitch": true,
  "val_check_interval": 2000,
  "valid_infer_interval": 2000,
  "valid_monitor_key": "val_loss",
  "valid_monitor_mode": "min",
  "validate": false,
  "warmup_updates": 1000,
  "weight_decay": 0,
  "work_dir": "",
  "world_size": -1
}
| load 'model' from 'checkpoints/audio2motion_vae/model_ckpt_steps_400000.ckpt', strict=True
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'checkpoints/motion2video_nerf/may_torso/lm3d_radnerf_torso.yaml', 'checkpoints/motion2video_nerf/may_torso/config.yaml']
| load 'model' from 'checkpoints/motion2video_nerf/may_torso/model_ckpt_steps_250000.ckpt', strict=True
trainval: Smooth head trajectory (rotation and translation) with a window size of 7
/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/tasks/radnerfs/dataset_utils.py:266: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.lm68s = torch.tensor(self.lm2ds[:, index_lm68_from_lm478, :])
/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py:184: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  eye_area_percents = torch.tensor(self.dataset.eye_area_percents)
Extracted wav file (16khz) from data/raw/val_wavs/MacronSpeech.wav to data/raw/val_wavs/MacronSpeech_16k.wav.
Loading the HuBERT Model...
/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading the Wav2Vec2 Processor...
GeneFace++ is rendering... :   0%|                                                                                                                                | 0/296 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py", line 593, in <module>
    GeneFace2Infer.example_run(inp)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py", line 537, in example_run
    infer_instance.infer_once(inp)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py", line 196, in infer_once
    out_name = self.forward_system(samples, inp)
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py", line 523, in forward_system
    self.forward_secc2video(batch, inp)
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/inference/genefacepp_infer.py", line 477, in forward_secc2video
    model_out = self.secc2video_model.render(rays_o[i], rays_d[i], cond_inp[i], bg_coords, poses[i], index=i, staged=False, bg_color=bg_color, lm68=lm68s[i], perturb=False, force_all_rays=False,
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/modules/radnerfs/radnerf_torso_sr.py", line 177, in render
    sigmas, rgbs, ambient = self(xyzs, dirs, cond_feat, ind_code)
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/modules/radnerfs/radnerf.py", line 117, in forward
    pos_feat = self.position_embedder(position, bound=self.bound) # spatial feat f after E^3_{spatial} 3D grid in the paper
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/modules/radnerfs/encoders/gridencoder/grid.py", line 159, in forward
    outputs = grid_encode(inputs, self.embeddings, self.offsets, self.per_level_scale, self.base_resolution, inputs.requires_grad, self.gridtype_id, self.align_corners, self.interp_id)
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/dkd/anaconda3/envs/gene/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 98, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/dkd/Data_4TDISK/hby/GeneFacePlusPlus-main/modules/radnerfs/encoders/gridencoder/grid.py", line 57, in forward
    outputs = outputs.permute(1, 0, 2).reshape(B, L * C)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by xuduo18311199384** [comment]
这个怎么解决的呢？

**Comment by huiceli** [comment]
> 这个怎么解决的呢？

我的是cuda版本不对，nvidia-smi看的那个cuda版本，但我在其他地方也碰到过这个报错，有一个是把命令的--debug去掉。

**Comment by jvel07** [comment]
@huiceli how did you solve this exactly? It would be amazing if you could provide the solution, please.
