### ISSUE TITLE
No background Image bg.jpg found

### ISSUE THREAD

**Issue by Ahmer-444** [yerfor/GeneFacePlusPlus#15]
Hi @yerfor,

Thank you for your assistance.

I'm currently trying to understand at which stage the background image `bg.jpg` file is created in the codebase. However, I couldn't locate its generation in the specified script:

[Link to the script](https://github.com/yerfor/GeneFacePlusPlus/blob/5d34524f2f652ab4a151d8245b2cea03f6bcdc34/data_gen/runs/binarizer_nerf.py#L198)

```
Traceback (most recent call last):
  File "/home/paperspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 334, in <module>
    binarizer.parse(video_id)
  File "/home/paperspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 313, in parse
    ret = load_processed_data(processed_dir)
  File "/home/paperspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 199, in load_processed_data
    assert os.path.exists(background_img_name)
AssertionError
```

**Comment by yerfor** [comment]
Hi, bg.jpg is extracted during runing data_gen/utils/extract_segment_imgs.py.  Please pull the latest commit, which could print more detailed logs.

**Comment by Ahmer-444** [comment]
I've successfully completed this step; however, I couldn't locate the `bg.jpg` file anywhere, and upon inspecting the code, I couldn't find any references to the `bg.jpg` code. Instead, I found a folder named `bg_imgs/`.

**Comment by yerfor** [comment]
Yes, bg_imgs/ is the per-frame background segments, which are intermediates that are used to extract a single global inpainted background image. Please check the log, is there any hint that points to an error?
