### ISSUE TITLE
python data_gen/utils/process_video/extract_segment_imgs.py 卡死在70%

### ISSUE THREAD

**Issue by zhuxiu1234** [yerfor/GeneFacePlusPlus#16]
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/58240847/b2d125da-1a68-4502-a79d-4aa694ee6fbb)

**Comment by zhuxiu1234** [comment]
原因：内存爆了

**Comment by yerfor** [comment]
Hi, you can pull the latest code, in which we should have improved the memory usage in the extracting segment process.

**Comment by WuCongfeng** [comment]
可以增加内存或者，把视频缩短
