### ISSUE TITLE
Training script (may not a bug)

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#17]
if __name__ == '__main__':
    set_hparams()
    # clear_gpus()
    run_task()
    try:
        set_hparams()
        run_task()
    except KeyboardInterrupt:
        if hparams['init_method'] == 'file':
            # on exit, remove the shared file in nfs for DDP
            exp_name = hparams['exp_name']
            shared_file_name = f'/home/tiger/nfs/pytorch_ddp_sharedfile/{exp_name}'
            if os.path.exists(shared_file_name):
                os.system(f"rm -r {shared_file_name}")

tasks/run.py: line21-line34，为什么set_hparams()和run_task()都运行了两遍

**Comment by yerfor** [comment]
Thanks for pointing out that, I have delete the redundant lines.
