### ISSUE TITLE
训练 Head NeRF 模型和训练 Torso NeRF 模型，需要修改参数eye_blink_dim才能训练，但是最后合成视频还是有问题

### ISSUE THREAD

**Issue by marsjin** [yerfor/GeneFacePlusPlus#171]
修改参数
# egs/datasets/May/lm3d_radnerf_sr.yaml:29:eye_blink_dim: 8
# egs/datasets/May/lm3d_radnerf_sr.yaml:29:eye_blink_dim: 8
推理测试：训练原视频效果如下
<img width="1534" alt="image" src="https://github.com/yerfor/GeneFacePlusPlus/assets/11713481/aefc92e7-7bbd-4118-9c00-0bec1cd254bd">
用自己的视频效果没法看了
<img width="1536" alt="image" src="https://github.com/yerfor/GeneFacePlusPlus/assets/11713481/79895d36-73fe-4440-a6c9-6a27b64ad167">

请教一下，你是否遇到过这个问题，如何解决这个问题的呢？

**Comment by fenghe12** [comment]
您好，请问您怎么跑起来训练的，我这改了参数 eye_blink_dim为8之后直接报了一个core dump的错误：
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/152588485/92c540a2-1890-45c9-a2ef-6bb6ee3250fd)
