### ISSUE TITLE
pip install ./modules/radnerfs/encoders/freqencoder -v 报错window10 conda环境

### ISSUE THREAD

**Issue by StartHua** [yerfor/GeneFacePlusPlus#18]
(genefaceFace) F:\AI\GeneFacePlusPlus-main>pip install ./modules/radnerfs/encoders/freqencoder -v
Using pip 23.3.1 from D:\python\Anaconda\envs\genefaceFace\lib\site-packages\pip (python 3.9)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing f:\ai\genefaceplusplus-main\modules\radnerfs\encoders\freqencoder
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "F:\AI\GeneFacePlusPlus-main\modules\radnerfs\encoders\freqencoder\setup.py", line 30, in <module>
      raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
  RuntimeError: Could not locate a supported Microsoft Visual C++ installation
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'D:\python\Anaconda\envs\genefaceFace\python.exe' -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'F:\\AI\\GeneFacePlusPlus-main\\modules\\radnerfs\\encoders\\freqencoder\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-n0t446or'
  cwd: F:\AI\GeneFacePlusPlus-main\modules\radnerfs\encoders\freqencoder\
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yerfor** [comment]
Sorry, we haven't try installing our project on Windows.

**Comment by lymGitHub0123** [comment]
安装最新版的 MSVC
