### ISSUE TITLE
Keeping head movement and sync of RAW source video after inference.

### ISSUE THREAD

**Issue by lipsynthesis** [yerfor/GeneFacePlusPlus#20]
What a cool project, started playing with it asap it arrived to the land of Github. Thank you Author.

Inference modifies outcome head movement and mask won't have good alignment when pasting it to original/raw video. Out of ideas how I could align it better. Any suggestions?

https://github.com/yerfor/GeneFacePlusPlus/assets/156137132/919f2550-b290-4e8f-b78d-a2a732343baa

**Comment by yerfor** [comment]
Hi, given the provided video, I suspect that you are utilizing GeneFace++ for rendering the lower-half face in a GT video. The mentioned mismatch might be partially caused by the error during the face tracking (`data_gen/utils/process_video/fit_3dmm_landmark.py`). But I'd like to suggest you to try to modify the line in the inference script that smoothes the driving head pose, which may cause a mismatch between the head pose in GT video and the (smoothed) driving pose that actually drive the NeRF-based renderer.

https://github.com/yerfor/GeneFacePlusPlus/blob/ba5d36e9ff3f0bb79ff4027bafaa5e630280c00e/inference/genefacepp_infer.py#L125 

To do so, change the above line to `hparams['infer_smooth_camera_path_kernel_size'] = 1`

**Comment by lipsynthesis** [comment]
Thank you for your answer, that was more than a kind.

Actually I am rendering full GT video, just cutting the mask and pasting to original video to avoid unrealistic eyes, forehead, ears and achieving better quality of hair and other parts of face, which for our experiment do not really need editing/modelling.

Getting definitely closer, still not perfectly synced yet. Edited hparams(the one you suggested) and also few lines in base.yaml(egs_bases).

https://github.com/yerfor/GeneFacePlusPlus/assets/156137132/ba023d89-c564-44cb-9b60-866f8e8ba6d4

Anything else that might add padding or smoothing that might cause original video and result not sync perfectly?

**Comment by lipsynthesis** [comment]
We are there. Studying and testing one by one helped us to reach the goal. 

Turned off all the smoothing from pretty much everywhere possible without errors and added a step in the end to convert the video to 60fps helped us to reach the goal to be synced with raw video. Thanks for the help and awesome project.

**Comment by yunyu** [comment]
@lipsynthesis What else did you turn off? I turned off smooth_features_xd for euler/trans as well as camera motion smoothing (all I could find in the inference code), and am still getting a mismatch. Did you also turn off smoothing during training, like in fit_3dmm_landmark?

**Comment by lipsynthesis** [comment]
Yes, we went way beyond changing just inference settings. 

https://github.com/yerfor/GeneFacePlusPlus/assets/156137132/3e1f2719-06d8-4099-a6d5-ef2367d59aba

This is no torso(artifacts under the chin) trained example masked to original video, 25 fps(60 fps was quick fix) to see the mask movement compared to original. Still can spot some and we will come back to it when needed. Didn't go much further as been busy with different project and to get perfect 1:1 with most likely needs code editing and better understanding the workflow.

If you up for collaboration, let's do it!

**Comment by akshay288** [comment]
Hey @lipsynthesis I'm looking to do something similar. I'm curious what other settings you changed or post processing you did to get the output to be aligned with the original video.

Also happy to help in any way if you have any ideas!

**Comment by SakuraMaiii** [comment]
> Yes, we went way beyond changing just inference settings.
> 
>  test127.mp4 
> This is no torso(artifacts under the chin) trained example masked to original video, 25 fps(60 fps was quick fix) to see the mask movement compared to original. Still can spot some and we will come back to it when needed. Didn't go much further as been busy with different project and to get perfect 1:1 with most likely needs code editing and better understanding the workflow.
> 
> If you up for collaboration, let's do it!

Hi, may I ask if you could give me a hint on which files need to be modified? Thank you very much

**Comment by jryebread** [comment]
hey @lipsynthesis interested in collabing on output as well! pls email me james@chatshape.com

**Comment by robertschoenholz** [comment]
hello hello, did someone manage to match the movement 100%?
