### ISSUE TITLE
Instant Motion-to-Video Motion

### ISSUE THREAD

**Issue by carthagan** [yerfor/GeneFacePlusPlus#21]
Amazing work, you did a wonderful job with this project! I was wondering about the Real-Time inference possibility. Could you direct us to where to look in order to stream the audio (or camera feed) that will drive the Nerf?

**Comment by yerfor** [comment]
Hi, maybe you should combine the `audio2secc` and `secc2video` method in the inference script into a combined function to achieve stream inference.

**Comment by mrhanCH** [comment]
Hello, I am also very interested in this. Do you have any solutions for real-time generation?

**Comment by mrtpk** [comment]
Checking in to see if anybody have done this.
