### ISSUE TITLE
训练 Head NeRF 模型到8万多步时崩了

### ISSUE THREAD

**Issue by charryshi** [yerfor/GeneFacePlusPlus#225]
python tasks/run.py --config=egs/datasets/macron/lm3d_radnerf_sr.yaml --exp_name=motion2video_nerf/macron_head --reset
看日志到8万多步崩了，看到后面的日志是
Traceback (most recent call last):
  File "/home/user/GeneFacePlusPlus/tasks/radnerfs/radnerf_sr.py", line 293, in
 _training_step
    current_ambient_loss = loss_output['ambient_loss'].item()
AttributeError: 'int' object has no attribute 'item'
| WARNING: ERROR calculating ambient loss

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/2d8bd26b-031c-4472-b099-2756e4289f6d">

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/5b70ae61-836c-41b5-985b-4966123899b3">

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/8e8ca598-8b86-4039-900b-8afe84585fef">

lm3d_radnerf_sr.yaml的参数没改啥
target_ambient_loss: 1.0e-6。（使用了建议的男性参数）
eye_blink_dim: 2  （修改和lm3d_radnerf_torso_sr.yaml中eye_blink_dim默认值一致了）
出问题的训练视频时长5分多一点

同样的参数在另外一个1分多钟的测试视频中跑没问题
![image](https://github.com/user-attachments/assets/723043ec-bd63-4fd4-a120-f7e06558c31e)

麻烦请问一下可能的问题原因，谢谢了。

**Comment by foshanfm** [comment]
其实已经够了吧，8万多步了

**Comment by abdur75648** [comment]
Hey @charryshi, were you able to figure out the cause of the problem? Can you please explain what was causing this & how was this fixed?
