### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config=egs/datasets/May/lm3d_radnerf_sr.yaml --exp_name=motion2video_nerf/may_head --reset

### ISSUE THREAD

**Issue by einsqing** [yerfor/GeneFacePlusPlus#23]
![1707096824449](https://github.com/yerfor/GeneFacePlusPlus/assets/7685948/8533a85a-697c-4931-aead-9efbbc76bda8)

When will this training stop?

**Comment by einsqing** [comment]
![1707097895141](https://github.com/yerfor/GeneFacePlusPlus/assets/7685948/dd0d804e-afdf-400f-8a3c-614896df0d1e)
Is this normal？

**Comment by yerfor** [comment]
See `max_updates` and `lpips_start_iters` in the .yaml config file. 

Yes, the learning curve seems normal.
