### ISSUE TITLE
你好，训练出现loss值nan

### ISSUE THREAD

**Issue by laishujie** [yerfor/GeneFacePlusPlus#24]
你好，训练过程在最后阶段会出现loss值nan的情况，这属于正常现象吗？随后程序就出现了错误。
![1](https://github.com/yerfor/GeneFacePlusPlus/assets/16934884/d939a0c8-0f90-4226-bace-74726a42704e)
1.这是因为训练过头导致的吗？自定义人物训练时，我是按照默认may的配置训练的，是要调整步数才能不出现这个错误吗？
2.还有推理的时候，可以只推理头部模型吗？torso_ckpt我想不训练，因为为要贴回原视频，想保证躯干一致性。
3.4090跑了8个小时才训练完头部，这时间正常吗
感谢您的回答

**Comment by yerfor** [comment]
1. 可以看一下tensorboard, 把lpips关掉或者调小一点试试；或者适当调整学习率和clip_grad_norm，
2. 可以，在infer的时候指定--head_ckpt，把--torso_ckpt设置为空字符串即可
3. 正常

**Comment by laishujie** [comment]
> 1. 可以看一下tensorboard，把lpips关掉或者调小一点尝试；或者适当调整学习率和clip_grad_norm，
> 2. 可以，在infer的时候指定--head_ckpt，把--torso_ckpt设置为空字符串即可
> 3. 正常

好的，感谢你的回答。
1.我看了tensorboard，其中有验证这个loss值越来越大,然后nan。我在尝试调整下值看看最新的训练效果。
![loss](https://github.com/yerfor/GeneFacePlusPlus/assets/16934884/28db3ab9-dc78-471c-95d7-bfead8552c32)

2.我把torso_ckpt设置为空字符串，推理出之后脖子不见了。是只能训练躯干吗？如何保留原有视频的脖子
3.我推理出来的结果，不会眨眼睛。是我那个部分出错了吗？我倒是看到分割阶段有一些异常，和这有关系吗？
![00000000](https://github.com/yerfor/GeneFacePlusPlus/assets/16934884/3e017017-35c0-4940-90cd-3df77e814322)

**Comment by yerfor** [comment]
1. 你可以看一下训练radnerf_sr 头部模型时，计算mse loss的过程，就是把预测的head和gt torso做alpha blending得到最终图像的。这个在infer的代码里没有实现，可能需要自己修改一下代码。
2. 是否可以发一下训练视频，我本地debug一下。

**Comment by laishujie** [comment]
> 1. 你可以看一下训练radnerf_sr 头部模型时，计算mse loss的过程，就是把预测的head和gt torso做alpha blending得到最终图像的。这个在infer的代码里没有实现，可能需要自己修改一下代码。
> 2. 是否可以发一下训练视频，我本地debug一下。

1.好的，我尝试自己改一改
2.素材我已经发你邮件zhenhuiye@zju.edu.cn了，因为是从1080p裁减下来的，素材质量较为一般。

**Comment by yerfor** [comment]
2. 可以是现在cond_type: idexp_lm3d_normalized 对眨眼时的眼睛表示有些问题，我之后会尝试一下其他的方式单独表示眼睛位置。
3. 可能是素材相关

**Comment by yerfor** [comment]
你好，我们更新了infer的代码，我们发现之前对idexp_lm3d的clamp操作可能会一定程度上破坏预测的动作并降低lip sync。现在的版本应该能带来更准确的唇形。相应的，眨眼动作也从原来无法控制眨眼到现在可以部分控制眨眼（很遗憾，在提供的May模型中我们发现只能实现半闭半睁的效果，我会在后续额外引入眨眼的condition来提升眨眼的控制效果）。

由于目前讨论的问题已经超出了本issue原来讨论的范畴，或许我们可以开一个新的issue来进一步讨论。
