### ISSUE TITLE
Error when extracting imgaes

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#26]
When I run the 'extract_segment_imgs.py', and extract the image with mediapipe:

I0000 00:00:1707100259.740940   41936 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1707100259.741208   41936 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
X connection to :1.0 broken (explicit kill or server shutdown).
X connection to :1.0 broken (explicit kill or server shutdown).

**Comment by laishujie** [comment]
--force_single_process 加上这个参数在执行看看。

**Comment by ChengsongLu** [comment]
> --force_single_process 加上这个参数在执行看看。

可以的，谢了!

**Comment by notedit** [comment]
--force_single_process  确实可以 不过处理速度太慢了
