### ISSUE TITLE
你好，请问为什么推理后画质降低了？Hello, may I ask why the picture quality is reduced after inference?

### ISSUE THREAD

**Issue by o576212113** [yerfor/GeneFacePlusPlus#29]
你好，请问为什么推理后画质降低了？
Hello, may I ask why the picture quality is reduced after inference?
![微信图片_20240205234448](https://github.com/yerfor/GeneFacePlusPlus/assets/41183969/287d8c68-19ff-4afd-9ab3-314772c9bb24)

**Comment by yerfor** [comment]
Hi, please check that x264 codec of ffmpeg is correctly installed. Or you can check the file size of the synthesized file. Ideally, it should be ~ 1.x MB if the ffmpeg is work as expected.

**Comment by o576212113** [comment]
源视频15MB，生成视频2.MB    Source video 15MB, generated video 2.MB

**Comment by o576212113** [comment]
(geneface) root@instance:~/onethingai-tmp/GeneFacePlusPlus# ffmpeg -version
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 12.3.0 (conda-forge gcc 12.3.0-5)
configuration: --prefix=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-cc --cxx=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-c++ --nm=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-nm --ar=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-gnutls --enable-libmp3lame --enable-libvpx --enable-libass --enable-pthreads --enable-vaapi --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/pkg-config
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100

**Comment by o576212113** [comment]
> 您好，请检查ffmpeg的x264编解码器是否正确安装。或者您可以检查合成文件的文件大小。理想情况下，如果 ffmpeg 按预期工作，它应该约为 1.x MB。
源视频15MB，生成视频2.MB 源视频15MB，生成视频2.MB

**Comment by o576212113** [comment]
(geneface) root@instance:~/onethingai-tmp/GeneFacePlusPlus# ffmpeg -codecs | grep libx264
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.3.0 (conda-forge gcc 12.3.0-5)
  configuration: --prefix=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-cc --cxx=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-c++ --nm=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-nm --ar=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/x86_64-conda-linux-gnu-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libharfbuzz --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-gnutls --enable-libmp3lame --enable-libvpx --enable-libass --enable-pthreads --enable-vaapi --enable-libopenvino --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1706918361713/_build_env/bin/pkg-config
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 libopenh264 h264_cuvid) (encoders: libx264 libx264rgb libopenh264 h264_nvenc h264_vaapi)

**Comment by o576212113** [comment]
Loading the Wav2Vec2 Processor...
Injected blink to idexp_lm3d by directly editting.
GeneFace++ is rendering... :   0%|                                                                                                                                         | 0/296 [00:00<?, ?it/s]Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
GeneFace++ is rendering... : 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:07<00:00, 37.82it/s]
ImageIO is saving video using FFMPEG(h264) to may_demo.tmp.mp4: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:00<00:00, 411.38it/s]
Saved at may_demo.mp4

**Comment by yunyu** [comment]
I changed the ffmpeg settings to produce lossless outputs, and am still getting relatively low-res video compared to the original (and similar output to the original GeneFace). Could there be something off with the SR module?

**Comment by yerfor** [comment]
<img width="1497" alt="Snipaste_2024-02-06_14-31-07" src="https://github.com/yerfor/GeneFacePlusPlus/assets/48365204/f1418520-34d7-40a8-9be5-2e06f9d17d11">

Hi, above is the comparison between GT during validation. If the output video achieves similar image quality as the validation result, that okay. Or if there is a degradation from the validation, it might be a problem of ffmpeg.

If you want a better "high-res" result, you can increase the `lambda_lpips_loss` in the .yaml config file, from example, from 0.001 to 0.003.

**Comment by o576212113** [comment]
**### frame_5658_gt_512**
![frame_5658_gt_512](https://github.com/yerfor/GeneFacePlusPlus/assets/41183969/8a6a1bde-3d80-4d14-8a3a-11ef37c0af85)
**### frame_5658_sr**
![frame_5658_sr](https://github.com/yerfor/GeneFacePlusPlus/assets/41183969/815ae61a-d020-484f-bb23-28daada14cb0)

Much less clear

**Comment by o576212113** [comment]
https://github.com/yerfor/GeneFacePlusPlus/assets/41183969/c2d297d7-bede-4a02-9c54-20afc200204c

推理效果

**Comment by o576212113** [comment]
> <img alt="Snipaste_2024-02-06_14-31-07" width="1497" src="https://private-user-images.githubusercontent.com/48365204/302524142-f1418520-34d7-40a8-9be5-2e06f9d17d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODE2NzksIm5iZiI6MTcwNzM4MTM3OSwicGF0aCI6Ii80ODM2NTIwNC8zMDI1MjQxNDItZjE0MTg1MjAtMzRkNy00MGE4LTliZTUtMmUwNmY5ZDE3ZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA4MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTViNzNmNmViMjBmZGE5ODJhMjhmNTQ0MDE5ZDBkODM1YWM3NDIyNTYxZmE0YWM4NzhjYjcwMDdiYjIwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O3QNl5p9z9RaLaqJ7HfXrqUTa-FNoa08Dq6y_JIrIyc">
> 你好，上面是验证时 GT 和预测的比较。如果输出视频达到与验证结果相似的图像质量，那就没问题。或者如果验证出现降级，则可能是 ffmpeg 的问题。
> 
> 如果您想要更好的“高分辨率”结果，您可以增加`lambda_lpips_loss`.yaml 配置文件中的 ，例如从 0.001 到 0.003。

may I ask you how many steps were trained for this model

**Comment by o576212113** [comment]
> Hi, please check that x264 codec of ffmpeg is correctly installed. Or you can check the file size of the synthesized file. Ideally, it should be ~ 1.x MB for a 10-second-long video clip if the ffmpeg is work as expected.

Why the reasoning out of the video, not blink?

**Comment by yerfor** [comment]
> > <img alt="Snipaste_2024-02-06_14-31-07" width="1497" src="https://private-user-images.githubusercontent.com/48365204/302524142-f1418520-34d7-40a8-9be5-2e06f9d17d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODE2NzksIm5iZiI6MTcwNzM4MTM3OSwicGF0aCI6Ii80ODM2NTIwNC8zMDI1MjQxNDItZjE0MTg1MjAtMzRkNy00MGE4LTliZTUtMmUwNmY5ZDE3ZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA4MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTViNzNmNmViMjBmZGE5ODJhMjhmNTQ0MDE5ZDBkODM1YWM3NDIyNTYxZmE0YWM4NzhjYjcwMDdiYjIwOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O3QNl5p9z9RaLaqJ7HfXrqUTa-FNoa08Dq6y_JIrIyc">
> > 你好，上面是验证时 GT 和预测的比较。如果输出视频达到与验证结果相似的图像质量，那就没问题。或者如果验证出现降级，则可能是 ffmpeg 的问题。
> > 如果您想要更好的“高分辨率”结果，您可以增加`lambda_lpips_loss`.yaml 配置文件中的 ，例如从 0.001 到 0.003。
> 
> may I ask you how many steps were trained for this model

Hi, please pull the latest commit, in which we have address the blink issue.
