### ISSUE TITLE
推理时报错_backend.grid_encode_forward(inputs, embeddings, offsets, outputs, B, D, C, L, S, H, dy_dx, gridtype, align_corners, interpolation) TypeError: grid_encode_forward(): incompatible function arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by gaoleihero** [yerfor/GeneFacePlusPlus#3]
我在运行时报错，提示参数有问题
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/31463641/9812fa93-3b87-43e5-9f68-a7c46fdccfe2)
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/31463641/6cb7e684-05f4-4a9b-b158-7e03e23bc633)

**Comment by yerfor** [comment]
Hi please check whehter the cuda extensions are correctly installed. To install the extensions, you need to locally install CUDA using .run file on the Nvidia official website (https://developer.nvidia.com/cuda-downloads?target_os=Linux). And the CUDA version should be the same as your python CUDAtoolkit's version. Finally run  `bash docs/prepare_env/install_ext.sh` to install.
