### ISSUE TITLE
 Poor Outcome in Custom Training - Help Me Why?

### ISSUE THREAD

**Issue by Ahmer-444** [yerfor/GeneFacePlusPlus#30]
Hi @yerfor ,

Thank you for your outstanding work on this project and your support so far. 

The custom training results are disappointing despite a smooth process without errors. I'm open to providing more info for troubleshooting. Appreciate your help in resolving this.

https://github.com/yerfor/GeneFacePlusPlus/assets/16620925/2f552d24-fcf2-40af-9e80-4dcfdfc55caf

**Comment by yerfor** [comment]
Can you try to crop the video to make the human head bigger and train again?

**Comment by Net-Maker** [comment]
Great Issue！
Make me laugh!
hahahahahahahahahaha
