### ISSUE TITLE
[BUG] Dependency installation problem

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#32]
`sudo apt-get install libasound2-dev portaudio19-dev`

We still need to do this before installing pyaudio (as we did in GeneFace)

**Comment by ChengsongLu** [comment]
When I said 'before installing pyaudio', I mean before `pip install -r docs/prepare_env/requirements.txt -v`

**Comment by yerfor** [comment]
Got it, I'll update this in the next commit. Thanks for your comments.

**Comment by ChengsongLu** [comment]
Also, I recommand to change line 21 in file `data_gen/utils/process_audio/extract_hubert.py` from `local_path = '/home/tiger/.cache/huggingface/hub/models--facebook--hubert-large-ls960-ft/snapshots/ece5fabbf034c1073acae96d5401b25be96709d8'` to `local_path = '~/.cache/huggingface...........` to upspeed the inference process except the first time.

However, there are many other paths in the code that start with "/home/tiger/... ", and I'm not sure if they should be changed as well.

**Comment by yerfor** [comment]
Good suggestions! I will handle this in the next commit.
