### ISSUE TITLE
can this project use in winserver2019/2022 or windows 10/11

### ISSUE THREAD

**Issue by lymGitHub0123** [yerfor/GeneFacePlusPlus#33]
can this project use in winserver2019/2022 or windows 10/11?

**Comment by lymGitHub0123** [comment]
RuntimeError: Windows not yet supported for torch.compile....... 

T_T

**Comment by yerfor** [comment]
Hi, you can disable torch.compile by set `torch_compile: False` in the .yaml config file.

**Comment by SakuraMaiii** [comment]
> torch_compile: False

hey sir，where is the torch.compile,i only found it in genefacepp.py
 
![888](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/378c1f46-d889-42da-b64d-4b4bc7d2fec1)
