### ISSUE TITLE
FileNotFoundError: No such file: '/home/ubuntu/GeneFacePlusPlus/data/processed/videos/xxxx/inpaint_torso_imgs/00003486.png'

### ISSUE THREAD

**Issue by notedit** [yerfor/GeneFacePlusPlus#34]
Hi，I am training GeneFace++ with my own videos,   In the  Step4: Use the commandlines above to train the NeRF.

```
python tasks/run.py --config=egs/datasets/xxxx/lm3d_radnerf_sr.yaml --exp_name=motion2video_nerf/xxxx_head --reset
```
The error message:
```
FileNotFoundError: No such file: '/home/ubuntu/GeneFacePlusPlus/data/processed/videos/xxxx/inpaint_torso_imgs/00003486.png'
```
In fact  there is no 00003486.png.  

Any way to fix this?

**Comment by notedit** [comment]
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/480864/a27bed66-0200-4c42-bdd1-53b19f29a439)

**Comment by lipsynthesis** [comment]
You need to process the video before. 

bash data_gen/runs/nerf/run.sh <VIDEO_ID>

After that, there will be all the files for training and inference.

**Comment by notedit** [comment]
> You need to process the video before.
> 
> bash data_gen/runs/nerf/run.sh <VIDEO_ID>
> 
> After that, there will be all the files for training and inference.

I have already done that.

**Comment by jiuqing1851** [comment]
1. Have you solved it? I encountered the same issue.
