### ISSUE TITLE
BAD inference result on my training data.

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#36]
I have follow all the instructions that required to train a motion2video model. The inference result looks good on the model I trained with the data 'May.mp4' (not using the public model) as follow:
https://github.com/yerfor/GeneFacePlusPlus/assets/61783323/e8f99852-aa26-4d80-b6d0-51e9ede51ece

But when I use this video to train a model:
https://github.com/yerfor/GeneFacePlusPlus/assets/61783323/bee54361-9803-4d33-95e7-995611ba649e

The result is really bad like this:
https://github.com/yerfor/GeneFacePlusPlus/assets/61783323/66d69064-b4db-4d46-a2c4-11c486765d92

I am sure all the settings are the same between this two trainings.

**Comment by yerfor** [comment]
Hi, you could try center crop the training video to make the head segment larger. Like this:
<img width="498" alt="image" src="https://github.com/yerfor/GeneFacePlusPlus/assets/48365204/46dd0355-e7c6-4cd1-bb85-9fa35974c81f">
