### ISSUE TITLE
Inference commands failing

### ISSUE THREAD

**Issue by jamesrgallen** [yerfor/GeneFacePlusPlus#38]
Hi, thanks for your great work on this.

I am experiencing an error when I try and inference the may test clip:

![Screenshot from 2024-02-07 13-43-04](https://github.com/yerfor/GeneFacePlusPlus/assets/68879576/af3b761f-85c9-4d5c-8ecf-0bd642649b6b)

Any help appreciated!

**Comment by yerfor** [comment]
use `--torso_ckpt=checkpoints/motion2video_nerf/may_torso` instead of `--torso_ckpt=motion2video_nerf/may_torso`
