### ISSUE TITLE
运行时报错 ModuleNotFoundError: No module named '_raymarching_face'

### ISSUE THREAD

**Issue by huipengo** [yerfor/GeneFacePlusPlus#4]
GeneFacePlusPlus/modules/radnerfs/raymarching/raymarching.py", line 10, in &lt;module&gt;
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

**Comment by yerfor** [comment]
Hi, don't forget to install the cuda-extension by `bash docs/prepare_env/install_ext.sh`.

 Also note that, to install the extensions, you need to locally install CUDA using `.run` file on the Nvidia official website (https://developer.nvidia.com/cuda-downloads?target_os=Linux). And the CUDA version should be the same as your python CUDAtoolkit's version.
