### ISSUE TITLE
Index Error when training custom video

### ISSUE THREAD

**Issue by jamesrgallen** [yerfor/GeneFacePlusPlus#40]
Hi, Thanks for your continued support!

I am trying to train a custom video however when I get to the head training portion I get this error:

**IndexError: index 13610 is out of bounds for dimension 0 with size 13000**
![Screenshot from 2024-02-07 19-01-26](https://github.com/yerfor/GeneFacePlusPlus/assets/68879576/119e2064-c660-41c0-9a74-170c80e50a70)

Any help appreciated. The video is 512x512 at 25fps (processed by the steps outlined in docs/process_data/guide.md)

**Comment by ChengsongLu** [comment]
You need to do this:

'Step2: copy a config folder egs/datasets/{Video_ID} following egs/datasets/May, remind to change video: May to video: {Video_ID}'

from https://github.com/yerfor/GeneFacePlusPlus/blob/main/docs/train_and_infer/guide.md

**Comment by yerfor** [comment]
In the .yaml config file, please increase the `individual_embedding_num: 13000` to a number that is larger than the number of frames in your own training video, such as 30000.

**Comment by jamesrgallen** [comment]
> In the .yaml config file, please increase the `individual_embedding_num: 13000` to a number that is larger than the number of frames in your own training video, such as 30000.

Thanks!
