### ISSUE TITLE
Trainning not stop in the 2nd statge

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#43]
I have set `lpips_start_iters: 140_000 max_updates: 150_000` in file 'lm3d_radnerf_sr.yaml'
and  set `lpips_start_iters: 140_000 num_updates: 150_000` in file 'lm3d_radnerf_torso_sr.yaml'

However, training of the head-NeRF can stop at 150,000 steps while training of the torso model does not.

**Comment by yerfor** [comment]
please set `max_updates` instead of `num_dates`
