### ISSUE TITLE
Inference demo in Chinese

### ISSUE THREAD

**Issue by ChengsongLu** [yerfor/GeneFacePlusPlus#44]
Original video (trainning data, 1min long):
https://github.com/yerfor/GeneFacePlusPlus/assets/61783323/5e040e3e-be2c-4661-915f-2fd67587c350

Inference video:
https://github.com/yerfor/GeneFacePlusPlus/assets/61783323/f2bda154-3046-4147-9d50-f625c2893fae

Settings:
lipips_start_iters: 140000
max_updates: 150000

Problems:
1. It doesn't blink.
2. The mouth stays half-open most of the time.
3. Most words are pronounced with similar mouth shapes (referring to the first few seconds of the inference video).

However, still a brilliant work in my opinion!

**Comment by yerfor** [comment]
As for problem 1. I'm currently working on this issue, and we are near to work it out. Please stay tuned for the in-coming commit.

As for probelm 2&3. Please add `--debug` when running `inference/genefacepp_infer.py`, the code will visualize several intermediates during the inference and can help figure out which part in the pipleine is not working as expected. As the training video is only 1minute long, it is common to see the predicted motion is correctly rendered by the NeRF. I'd suggest you try longer training video (such as 3minute as `May.mp4`)

**Comment by ChengsongLu** [comment]
Thanks for the answers.

I have another quesiton, are the pose changes in the inference video randomly determined by the model? (like when to nod the head, when to tilt the head, etc.)

**Comment by yerfor** [comment]
No, please refer to `prepare_batch_from_inp(self, inp)` in the inference script. The infer pose is extracted from the training dataset. You can use pose from an external video, which may require several modifications.

**Comment by yerfor** [comment]
The eyeblink is solved in the latest commit.
