### ISSUE TITLE
Unable to infer on long audio

### ISSUE THREAD

**Issue by Anish703** [yerfor/GeneFacePlusPlus#48]
Hi,

I trained my own models based on the docs provided, while everything works smoothly for audio above 10 secs and below 30 secs, anything longer returns "Killed" in the bash terminal. Please find a screenshot below.

![image](https://github.com/yerfor/GeneFacePlusPlus/assets/55701851/2a3d20dc-f73f-4ef2-a618-ed78def8ba18)

**Comment by yerfor** [comment]
Hi, it seems like a out-of-memory issue. We will handle it in the next commit.

**Comment by benchrus** [comment]
I want to know the recommended video length for training head nerf and torso.
And what about drv_aud length? Should it be shorter than the training video?

**Comment by yerfor** [comment]
Hi, please update to the latest commit, and set `--low_memory_usage` option when running the inference code.
