### ISSUE TITLE
data processing has issue: extract_segment_imgs.py hangs

### ISSUE THREAD

**Issue by wnqw** [yerfor/GeneFacePlusPlus#50]
Dear author, it seems the extract_segment_imgs.py hangs when processing the data. What might be the solutions to resolve this? (The command I used is:python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 --total_gpus 0)

<img width="1559" alt="Screenshot 2024-02-12 at 6 57 21 PM" src="https://github.com/yerfor/GeneFacePlusPlus/assets/57780182/26175c70-0c47-47e0-a903-dea8a8b8d587">

**Comment by notedit** [comment]
--force_single_process 加上这个参数在执行看看，我这里也遇到卡住的情况，加上这个之后可以，但非常慢。
