### ISSUE TITLE
"RuntimeError: Windows not yet supported for torch.compile"

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#51]
hey sir，I have a question about how to infer on Win10. Based on your previous feedback, I did not find the _**torch compile:False**_ in the_**. yaml**_ file. Thank you very much
![888](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/ba7baa9e-7a48-4d9e-bad7-6abd69ba32fd)

**Comment by yerfor** [comment]
You can comment the line that `torch.comiple` the model.
