### ISSUE TITLE
Why does the head flicker

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#54]
https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/9e59af22-f456-4fdc-ac2a-964930a80575

**Comment by SakuraMaiii** [comment]
At the end of the video, the head will flicker, and I tested other inference videos as well

**Comment by yerfor** [comment]
Please add --debug when running the inference code. I suspect it is caused by the predicted expression.

**Comment by yerfor** [comment]
Hi, it might caused by the padded HuBERT. Please pull the latest commit, and it should be solved.

**Comment by SakuraMaiii** [comment]
> Hi, it might be caused by the padded HuBERT. Please pull the latest commit, and it should be solved.

Thank you sir

**Comment by wangchenwc** [comment]
用最新的代码，还是会有这个情况，只要人物眨眼，就会出现。
