### ISSUE TITLE
An error occurred while building the model: 'RADNeRFDataset' object has no attribute 'lm68s'

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#55]
Hi:
When training Torso, the code automatically exited after running, so I added code to capture errors in "radnerf-torso_sr. py". Can you tell me how to fix this error

**Comment by SakuraMaiii** [comment]
<img width="873" alt="radnerf_torso_sr py" src="https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/d6ad2d4c-f959-4efa-9137-df2aeb052392">

**Comment by SakuraMaiii** [comment]
i got it,It's my fault

**Comment by fjesikfjdskl** [comment]
Hello, how did you solve this problem?
