### ISSUE TITLE
How to use `--drv_pose` param

### ISSUE THREAD

**Issue by akshay288** [yerfor/GeneFacePlusPlus#56]
Hey, thank you for releasing this model! The lipsync quality is some of the best I've seen :)

I'm curious what the `--drv_pose` does. The help translates to ("Currently, only the poses of the source video are supported, including starting from the beginning and specifying the interval. In-the-wild poses are not supported for the time being.") and the default is `nearest`.

I'm curious what `nearest` means and how would I specify different poses in the source video. In a perfect world I would like the head movement to perfectly match the source video as close as possible so I can paste the face back on to the original video :) 

Thanks again!

**Comment by yerfor** [comment]
Hi, `nearest` is a placeholder. By default, the head pose sequence is exacted from the training dataset, starting from the first frame of the training video and ends at the last frame. If the driving audio is longer than the training video, the head pose will be expanded by mirror index. 

In the current code, you can use different head poses by specifing a clip within the training video. For instance, set `--drv_pose=100-200` denotes the head pose is the 100th frame to 200th frame of the training video.

**Comment by SakuraMaiii** [comment]
> 嘿，谢谢你发布这个模型！口型同步质量是我见过的最好的:)
> 
> 我很好奇它有什么作用。帮助翻译为 （“目前，仅支持源视频的姿势，包括从头开始和指定间隔。暂时不支持野外姿势。默认值为 。`--drv_pose``nearest`
> 
> 我很好奇这意味着什么以及如何在源视频中指定不同的姿势。在理想情况下，我希望头部运动尽可能接近源视频，以便我可以将脸部粘贴回原始视频:)`nearest`
> 
> 再次感谢！

Hey.Have you solved the problem of pasting the inferred video back to the original video?

**Comment by SakuraMaiii** [comment]
> Hey, thank you for releasing this model! The lipsync quality is some of the best I've seen :)
> 
> I'm curious what the `--drv_pose` does. The help translates to ("Currently, only the poses of the source video are supported, including starting from the beginning and specifying the interval. In-the-wild poses are not supported for the time being.") and the default is `nearest`.
> 
> I'm curious what `nearest` means and how would I specify different poses in the source video. In a perfect world I would like the head movement to perfectly match the source video as close as possible so I can paste the face back on to the original video :)
> 
> Thanks again!


Hey.Have you solved the problem of pasting the inferred video back to the original video?

**Comment by SakuraMaiii** [comment]
> Hi, is a placeholder. By default, the head pose sequence is exacted from the training dataset, starting from the first frame of the training video and ends at the last frame. If the driving audio is longer than the training video, the head pose will be expanded by mirror index.`nearest`
> 
> In the current code, you can use different head poses by specifing a clip within the training video. For instance, set denotes the head pose is the 100th frame to 200th frame of the training video.`--drv_pose=100-200`

Hey sir.Even if I perform inference **starting from the first frame**, the video still **cant be pasted back to the original video**. It seems that some elements of the screen have deformed.Can you help me solve this problem? Thank you very much

![121](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/c4070776-9d96-4473-90e0-613c2c6b74b4)

**Comment by SakuraMaiii** [comment]
When I manually aligned the video, some elements were also missing from the video
![122](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/a9d5330f-9f2f-4082-8acf-cd225bfa6600)

**Comment by zxd147** [comment]
> 嗨，是一个占位符。默认情况下，头部姿势序列是从训练数据集中获取的，从训练视频的第一帧开始，到最后一帧结束。如果驾驶音频比训练视频长，则头部姿势将通过镜像索引扩展。`nearest`
> 
> 在当前代码中，您可以通过在训练视频中指定剪辑来使用不同的头部姿势。例如，set 表示头部姿势是训练视频的第 100 帧到第 200 帧。`--drv_pose=100-200`

[self.dataset.poses[i].unsqueeze(0) for i in range(start_idx, end_idx)]
索引是不是没对上，如果--drv_pose=100-200，实际上使用的是数据集里第101-201帧图片
