### ISSUE TITLE
A question about "smooth head trajectory"

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#58]
![Q](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/a63e239a-e446-424c-ab1c-02a7f20f71be)

Hi,sir
Before conducting head training, I noticed that the values for **blink embedding trainable parameters** and **dropout trainable parameters** were 0. Is this a normal phenomenon? Thank you

**Comment by yerfor** [comment]
Hi, it's normal. The value is too small and is rounded to 0.

**Comment by SakuraMaiii** [comment]
> 嗨，这很正常。该值太小，四舍五入为 0。

thank you sir
