### ISSUE TITLE
要训练自己的模型，postnet是必须训练的吗？

### ISSUE THREAD

**Issue by husthzy** [yerfor/GeneFacePlusPlus#6]
Audio2motion和postnet暂时无法训练的话，是不是意味着还不能训练自己的视频呢？

**Comment by yerfor** [comment]
你好，postnet不是必须的。现在提供的预训练模型也没有postnet。postnet是可以让动作更加具有目标人的行为习惯，目前还没有发布。

**Comment by yaleimeng** [comment]
@yerfor  后续能公开训练代码吗？既然在Todo list上面，强烈希望这一块也能早日开放出来与业内交流。

**Comment by yerfor** [comment]
这一部分会在论文被接收后公开
