### ISSUE TITLE
inference result blurry

### ISSUE THREAD

**Issue by lswc225** [yerfor/GeneFacePlusPlus#61]
This is a great project! 
this is my infrence result:
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/16609338/e8ade1e8-3547-4e0d-95b1-3ed56226614f)
head train 10w step.torso train step 1.4w step. head is blurry. how can i  fix it ? 
What is the recommended number of training steps,both head and torse. thanks.

**Comment by yerfor** [comment]
Consider crop the video to make the head larger in the frame. To se whether the artifact disappear.
