### ISSUE TITLE
求助！Inference ERROR: object of type 'int' has no len()

### ISSUE THREAD

**Issue by wangjingyuancuc** [yerfor/GeneFacePlusPlus#62]
求助！前几天用着好好的，今晚下载了最新的代码和各项文件，新装了下4090的机器，结果不能使用了，只要在blink mode里选了period，就会出现下面这个Extracted wav file (16khz) from /tmp/gradio/0d629616b6c2da040d8a0c066cd03885de3da994/2.wav to /tmp/gradio/0d629616b6c2da040d8a0c066cd03885de3da994/2_16k.wav.
Inference ERROR: object of type 'int' has no len()
Failed to generate

**Comment by wangjingyuancuc** [comment]
选none生成正常

**Comment by hnsywangxin** [comment]
同样的问题

**Comment by Guanyuansheng** [comment]
是需要重新训练吗？

**Comment by davideuler** [comment]
提了一个 MR 修复这个问题，附带加上了 Dockerfile.  你也可以手工修改一下代码来修复。

https://github.com/yerfor/GeneFacePlusPlus/pull/63
