### ISSUE TITLE
你好执行时 data_gen/utils/process_video/extract_segment_imgs.py 无响应

### ISSUE THREAD

**Issue by laishujie** [yerfor/GeneFacePlusPlus#7]
![17068654765467](https://github.com/yerfor/GeneFacePlusPlus/assets/16934884/2020240c-e594-498b-bbc1-f2e8344c8eb7)

**Comment by yerfor** [comment]
Hi, it seems to be an internal error in mediapipe. In my env, the EGL is not initialized and could work well in multiple process. 

Maybe you can change the line (https://github.com/yerfor/GeneFacePlusPlus/blob/3900669fdcd4c45bfb40eaf7c7fff191a8c03d7f/data_gen/utils/process_video/extract_segment_imgs.py#L298) to False and try to run in single process.

**Comment by laishujie** [comment]
> Hi, it seems to be an internal error in mediapipe. In my env, the EGL is not initialized and could work well in multiple process.
> 
> Maybe you can change the line (
> 
> https://github.com/yerfor/GeneFacePlusPlus/blob/3900669fdcd4c45bfb40eaf7c7fff191a8c03d7f/data_gen/utils/process_video/extract_segment_imgs.py#L298
> 
> ) to False and try to run in single process.

谢谢，可以执行了。但是执行的时候内存不断上涨，不会释放直到oom，想请问下这个又是什么问题
![企业微信截图_17068674311516](https://github.com/yerfor/GeneFacePlusPlus/assets/16934884/3fcc1ed8-ccb3-4a43-b99e-8c3f035711cf)

**Comment by yerfor** [comment]
Got it, we will optimize the memory usage in several days.

**Comment by Kizuna-AII** [comment]
> > Hi, it seems to be an internal error in mediapipe. In my env, the EGL is not initialized and could work well in multiple process.
> > Maybe you can change the line (
> > https://github.com/yerfor/GeneFacePlusPlus/blob/3900669fdcd4c45bfb40eaf7c7fff191a8c03d7f/data_gen/utils/process_video/extract_segment_imgs.py#L298
> > 
> > ) to False and try to run in single process.
> 
> 谢谢，可以执行了。但是执行的时候内存不断上涨，不会释放直到oom，想请问下这个又是什么问题 ![企业微信截图_17068674311516](https://private-user-images.githubusercontent.com/16934884/301803746-3fcc1ed8-ccb3-4a43-b99e-8c3f035711cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTY4NzgsIm5iZiI6MTcwNjg5NjU3OCwicGF0aCI6Ii8xNjkzNDg4NC8zMDE4MDM3NDYtM2ZjYzFlZDgtY2NiMy00YTQzLWI5OWUtOGMzZjAzNTcxMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2OTIyN2Y1NDIxZTQ4ZWQyMTViYWVhYThjNDRiY2Q1NTYwNWVhYmM5OTJiZjEwZGFiYzVkOTc0NjdlNTRiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_IBg3nA6N3dUCIbK_GBLoYMayOdU8WiL2RpZ71zYUQ)

Hi, we have updated the code of segmentation. You can have a try now!
In my test, the memory cost is reduced from about 100GB to about 4GB with a 5-minute test video.
