### ISSUE TITLE
训练val loss突变，过拟合了吧

### ISSUE THREAD

**Issue by wangchenwc** [yerfor/GeneFacePlusPlus#74]
<img width="377" alt="image" src="https://github.com/yerfor/GeneFacePlusPlus/assets/41559810/b9425371-e37f-4499-9c6e-30f38295eb99">
那预估的时候还是用250000步的么？

**Comment by Net-Maker** [comment]
一样的情况，mse loss的梯度消失了，请问您找到解决方案了吗？
