### ISSUE TITLE
No file called "mediapipe-in_bfm53201. npy"

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#76]
Hi sir，There is no file called "**mediapipe-in_bfm53201. npy**" in both Google Drive and BaiduYun Disk （As you say,this file was supposed to be in the path：**deep_3drecon/BFM/**）
![333](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/b5cb25b4-eb5a-4eec-bd69-ed18788f3f18)

**Comment by SakuraMaiii** [comment]
![444](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/47b45594-12f3-43e7-adec-0d390050bc68)

**Comment by jiennyteng** [comment]
I also met the error in the mediapipe's segmentation : malloc(): unaligned tcache chunk detected
do you meet similar error  ?

**Comment by yerfor** [comment]
Hi, it's okay, the missing file is not used by the 3DMM model.
