### ISSUE TITLE
为啥blink_mode=period时，每次眨眼就闪一下呢？

### ISSUE THREAD

**Issue by wangchenwc** [yerfor/GeneFacePlusPlus#80]

**Comment by wangchenwc** [comment]
https://github.com/yerfor/GeneFacePlusPlus/assets/41559810/42eda128-8950-4b2a-b87b-c7cb3c8085f6

类似于这种

**Comment by yerfor** [comment]
Hi, can you increase this `0.001` to a larger value like `0.01` or `0.05` to see whether it works.
 
https://github.com/yerfor/GeneFacePlusPlus/blob/dcd3f94c13b107aeffc9bc1947feeb1dba5990f7/inference/genefacepp_infer.py#L185

**Comment by Net-Maker** [comment]
你好，我试过了，这个问题还是存在，脸部在眨眼的时候会抽搐

**Comment by Net-Maker** [comment]
我将eye_blink_dim:修改为4之后，眨眼正常了，参考 #47
