### ISSUE TITLE
The validity during training is only 42%

### ISSUE THREAD

**Issue by SakuraMaiii** [yerfor/GeneFacePlusPlus#85]
![5112](https://github.com/yerfor/GeneFacePlusPlus/assets/97810888/af56381f-efd2-4b65-9fb5-c6a405b46404)

**Comment by benchrus** [comment]
I have experienced this for several times. Does this affect the result video?
I want to know why this happens.

**Comment by Zhihengliang** [comment]
I think it might be because your video duration is too short. 
Maybe you can try a 3 min video
