### ISSUE TITLE
Wrong predicted density/depth

### ISSUE THREAD

**Issue by Gina07** [yerfor/GeneFacePlusPlus#89]
Hi author, thanks for sharing this great work! I am training with a Chinese person video. And I found that after only 20k steps of training head_nerf, the predicted depth/density of nerf becomes wrong. As shown here 
![frame_2650](https://github.com/yerfor/GeneFacePlusPlus/assets/9716015/d3460799-0586-4ca3-b27b-de350bae62d3). This has a bad influence on the final rendering quality of the background, in which the bg is weird dynamic. Could you help provide some comments on how to resolve this issue? Many thanks.

**Comment by Gina07** [comment]
Found the issue: we should use 'com_imgs' instead of 'gt_imgs' as the GT for training. Closed.

**Comment by yerfor** [comment]
Hi, thanks for pointing out this, I have update the binarizer, it now points `gt_img_name` to the `com_imgs`.

**Comment by yunyu** [comment]
Looks like updating the binarizer breaks torso training – no predicted depth on torso. Working around this by binarizing again before torso training, but FYI

**Comment by yunyu** [comment]
Looks like this is causing torso training to fail, as the torso background is now the same for everything. Easily fixed by rerunning the binarizer with gt_imgs for training, but heads up

**Comment by jinqinn** [comment]
what's the difference between com_imgs and gt_imgs @yerfor
