### ISSUE TITLE
python data_gen/runs/binarizer_nerf.py --video_id=${VIDEO_ID}

### ISSUE THREAD

**Issue by einsqing** [yerfor/GeneFacePlusPlus#9]
![1706928800341](https://github.com/yerfor/GeneFacePlusPlus/assets/7685948/71981ed4-cf80-4d64-abdc-2e38176fa75f)

 No such file or directory: 'data/processed/videos/can/coeff_fit_mp.npy

**Comment by yerfor** [comment]
Hi, we can see that fit_3dmm raise a error that `MeshRasterizer` is not defined. Please check whether pytorch3d is well installed. If not, run this:
```bash
# Build from source, it may take a long time (Proxy is recommended if encountering the time-out problem)
pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
```

**Comment by MtYCNN** [comment]
> 您好，我们可以看到 fit_3dmm 引发了一个`MeshRasterizer`未定义的错误。请检查pytorch3d是否安装良好。如果没有，请运行以下命令：
> 
> ```shell
> # Build from source, it may take a long time (Proxy is recommended if encountering the time-out problem)
> pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
> ```

安装以后，仍然报这个错误怎么办

**Comment by jackiezhang11** [comment]
> > 您好，我们可以看到 fit_3dmm 引发了一个`MeshRasterizer`未定义的错误。请检查pytorch3d是否安装良好。如果没有，请运行以下命令：
> > ```shell
> > # Build from source, it may take a long time (Proxy is recommended if encountering the time-out problem)
> > pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
> > ```
> 
> 安装以后，仍然报这个错误怎么办

您好，这个问题解决了吗

**Comment by oncealong** [comment]
when I exec cmd 'python data_gen/utils/process_video/fit_3dmm_landmark.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 --reset  --debug --id_mode=global', the following message print:
```
reate rasterizer on device cuda:0cessed/videos/Lieu/debug_fit_3dmm.mp4..:   0%|                                                   | 0/250 [00:00<?, ?it/s]
rendering debug video to data/processed/videos/Lieu/debug_fit_3dmm.mp4..:   0%|                                                   | 0/250 [00:00<?, ?it/s]
data/raw/videos/Lieu.mp4 Not compiled with GPU support
finished 1 / 1 = 1.0000, failed 1 / 1 = 1.0000
process 0: fitting 3dmm ...: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:50<00:00, 50.85s/it]
all failed image names: ['data/raw/videos/Lieu.mp4']
All finished!
```

cr the code, the message only deal in debug mode.
```
    if debug:
        import imageio
        from utils.visualization.vis_cam3d.camera_pose_visualizer import CameraPoseVisualizer
        from data_util.face3d_helper import Face3DHelper
        from data_gen.utils.process_video.extract_blink import get_eye_area_percent
        face3d_helper = Face3DHelper('deep_3drecon/BFM', keypoint_mode='mediapipe')
    ...
        for i in tqdm.trange(min(250, len(frames)), desc=f'rendering debug video to {debug_name}..'):
            xy_cam3d_img = xy_camera_visualizer.extrinsic2pyramid(extrinsic[i], focal_len_scaled=0.25)

```

so exec the cmd without --debug:
```
python data_gen/utils/process_video/fit_3dmm_landmark.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 --reset  --id_mode=global
```

**Comment by zhieie** [comment]
![2024-05-10 19-32-02 的屏幕截图](https://github.com/yerfor/GeneFacePlusPlus/assets/169363304/cc6b9000-feb5-40be-a8a6-2787fa21c034)
我也遇到相同的问题,我尝试重新安装pytorch3d,并查看导已经安装成功.但是再执行

**Comment by zhieie** [comment]
执行 python data_gen/utils/process_video/fit_3dmm_landmark.py --ds_name=nerf --vid_dir=data/raw/videos/hawteen.mp4 --reset --debug --id_mode=global时,显示all failed image names: ['data/raw/videos/hawteen.mp4'],无法生成coeff_fit_mp
.npy
