### ISSUE TITLE
DDP not working

### ISSUE THREAD

**Issue by issaysa** [yerfor/GeneFacePlusPlus#94]
With multiple GPUs, training NeRF does not work. 
`CUDA_VISIBLE_DEVICES=0,1,2 python tasks/run.py --config=egs/datasets/May/lm3d_radnerf_sr.yaml --exp_name=motion2video_nerf/may_head --reset`
will show the error same as [here](https://github.com/yerfor/GeneFacePlusPlus/issues/71#issuecomment-1954508788)
```
chunk expects at least a 1-dimensional tensor
```
It seems  tensor.dim() becomes 0 in `scatter` function of `torch/nn/parallel/comm.py`.
It would be helpful if anybody could share some information about this.

**Comment by issaysa** [comment]
it was environment problem. I could fix this problem by using docker.
```
torch/nn/parallel/comm.py'                                                                                                                                   
has an incorrect size.                                                                                                                                                                                                      
  reported size: 10788 bytes
  actual size: 10824 bytes
```

**Comment by oncealong** [comment]
@issaysa Have you solved this problem?
