### ISSUE TITLE
在源代码中是没有postnet这个部分吗？

### ISSUE THREAD

**Issue by zckcola** [yerfor/GeneFacePlusPlus#95]
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/145427194/202c8265-e7c7-403b-89e3-77dae6f03517)
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/145427194/14fed90a-8a95-4de8-a5fa-c51e22b6650b)
m没有这个模块

**Comment by gongmm** [comment]
Release Training Code of Audio2Motion and Post-Net. (Maybe 2024.06.01)
