### ISSUE TITLE
stuck here when building wheel for pytorch 3d

### ISSUE THREAD

**Issue by zhuyang2356** [yerfor/GeneFacePlusPlus#97]
hello, I have been stuck with implementing pytorch3d for quite a long time.
I would like to see if someone can help.
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/43929214/51c5d4fb-e3da-47d6-81b4-9cc932fe14dd)
my command is as follows:
cd <GeneFaceRoot>
source <CondaRoot>/bin/activate
conda create -n geneface python=3.9
conda activate geneface
conda install conda-forge::ffmpeg # ffmpeg with libx264 codec to turn images to video

conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia

pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"

**Comment by SystemErrorWang** [comment]
same problem here, get this error:
`ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects`
when trying 
`pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`
